apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: hachikoapp/kuard:0.1
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP